/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        /* ── MD3 Light Tokens ── */
        "primary":                    "#004e51",
        "on-primary":                 "#ffffff",
        "primary-container":          "#11676b",
        "on-primary-container":       "#99e3e7",
        "primary-fixed":              "#a6eff3",
        "primary-fixed-dim":          "#8ad3d7",
        "on-primary-fixed":           "#002021",
        "on-primary-fixed-variant":   "#004f53",
        "secondary":                  "#1b6d24",
        "on-secondary":               "#ffffff",
        "secondary-container":        "#a0f399",
        "on-secondary-container":     "#217128",
        "secondary-fixed":            "#a3f69c",
        "secondary-fixed-dim":        "#88d982",
        "on-secondary-fixed":         "#002204",
        "on-secondary-fixed-variant": "#005312",
        "tertiary":                   "#851f00",
        "on-tertiary":                "#ffffff",
        "tertiary-container":         "#af2b00",
        "on-tertiary-container":      "#ffcabc",
        "tertiary-fixed":             "#ffdbd1",
        "tertiary-fixed-dim":         "#ffb5a1",
        "on-tertiary-fixed":          "#3b0800",
        "on-tertiary-fixed-variant":  "#881f00",
        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "error-container":            "#ffdad6",
        "on-error-container":         "#93000a",
        "background":                 "#f4faff",
        "on-background":              "#111d23",
        "surface":                    "#f4faff",
        "on-surface":                 "#111d23",
        "surface-variant":            "#d7e4ec",
        "on-surface-variant":         "#3e4946",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#e9f6fd",
        "surface-container":          "#e3f0f8",
        "surface-container-high":     "#ddeaf2",
        "surface-container-highest":  "#d7e4ec",
        "surface-dim":                "#cfdce4",
        "surface-bright":             "#f4faff",
        "surface-tint":               "#14696d",
        "outline":                    "#6e7976",
        "outline-variant":            "#bec9c5",
        "inverse-surface":            "#263238",
        "inverse-on-surface":         "#e6f3fb",
        "inverse-primary":            "#8ad3d7",
      },
      fontFamily: {
        sans:     ['Manrope', 'IBM Plex Sans Arabic', 'sans-serif'],
        headline: ['Plus Jakarta Sans', 'IBM Plex Sans Arabic', 'sans-serif'],
        body:     ['Manrope', 'IBM Plex Sans Arabic', 'sans-serif'],
      },
      keyframes: {
        'fade-in-up': {
          '0%':   { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-right': {
          '0%':   { opacity: '0', transform: 'translateX(-40px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%':      { opacity: '0.6' },
        },
      },
      animation: {
        'fade-in-up':    'fade-in-up 0.4s ease forwards',
        'slide-in-right':'slide-in-right 0.25s ease forwards',
        'pulse-soft':    'pulse-soft 2s ease-in-out infinite',
      },
      boxShadow: {
        'ambient': '0px 20px 40px rgba(17, 29, 35, 0.06)',
        'primary': '0 4px 20px rgba(0, 78, 81, 0.25)',
      },
    },
  },
  plugins: [],
}
